name: my-first-workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo "Welcome to my first workflow!"
      - name: checkout code
        uses: actions/checkout@v4 
      - name: list files
        run: ls -la
      - name: display date
        run: date
      - name: Show current working-directory
        run: pwd
      - name: Read files
        run: cat README.md 
      - name: List and Read files
        run: |
          echo "Listing all files in the current directory:"
          ls -la
          echo "Reading the contents of README.md:"
          cat README.md
## executing Third party libraries
      - name: Generate ASCII Artwork
        run: cowsay -f dragon " Run for cover, I am a Dragon... RAWR!" >> dragon.txt
      - name: view generated ASCII artwork
        run: cat dragon.txt
        ## THIS dragon.txt generated  in this workflow will not be persisted after the workflow completes because it is run on runner's ephemeral filesystem.
        ## because it is not saved as an artifact or pushed to a repository.
        
        
        
        
        
        
        
        
        
        
        
    
  


    