name: Context testing
on: push
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump Secret context
        env:
          SECRET_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRET_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  deploy: 
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    ## this job will execute or run only if it is part of main branch other wise  it will skip the job
    needs: dump_contexts_to_log
    steps:
      - name: Docker Run
        run: echo docker run -d -p 80:80 docker.io/cholaraju29/github-actions-nginx:latest
        ## this will run the docker container with the image name and tag
        ## it will run the container in detached mode and map the port 80 of the container to the port 80 of the host machine