name: Matrix Configuration
# The runnner comes pre-installed with docker
# so we can use docker commands directly
on:
  push:
  workflow_dispatch: 
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
# it will create 6 jobs
# 3 os  * 2 images = 6 jobs all these run in parallel
      
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info
      - name : Run images on ${{ matrix.os }}
        run:  docker run ${{ matrix.images }}
   
        
#   deploy-on-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Echo Docker Details
#         run: docker info
#       - name: Run images
#         run: docker run hello-world
 