name: Multi-job
on: [push,pull_request]
jobs: ### here we are defining multiple jobs in  a single workflow and each job can run independently in different runners or machines

  build_job:
    runs-on: ubuntu-latest
### Here we cannot use the needs tag as it creates loop or cycle 
    steps:
      - name: Install cowsay
        run: sudo apt-get install -y cowsay
      - name: Execute cowsay 
        run: cowsay -f dragon " Run for cover, I am a Dragon... RAWR!" >> dragon.txt
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Upload dragon text File
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file
          path: dragon.txt ##root of the repository
  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps: 
      - name: sleep for 10 seconds
        run: sleep 10
      - name: Download the upload artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file
      - name: Text File Exists
        run: grep -i "dragon" dragon.txt
      
  deploy_Job:
    needs: [build_job, test_job] ## Here we defined the dependency on both build_job and test_job use array syntax
    runs-on: ubuntu-latest
    steps:
      - name: Download the upload artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file
      - name: Read Text File
        run: cat dragon.txt
      - name: Deploy
        run: echo deploying ..........
        