name: Multi-job
on: [push,pull_request]
jobs: ### here we are defining multiple jobs in  a single workflow and each job can run independently in different runners or machines

  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: sudo apt-get install -y cowsay
      - name: Execute cowsay 
        run: cowsay -f dragon " Run for cover, I am a Dragon... RAWR!" >> dragon.txt
      - name: Sleep for 30 seconds
        run: sleep 30
  test_job:
    runs-on: ubuntu-latest
    steps: 
      - name: sleep for 10 seconds
        run: sleep 10
      - name: Text File Exists
        run: grep -i "dragon" dragon.txt
  deploy_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Read Text File
        run: cat dragon.txt
      - name: Deploy
        run: echo deploying ..........
        