name: Repository level secrets & variables
on: [push, pull_request]
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs: 
  docker_job:
    runs-on: ubuntu-latest
    
      #Here i removed DOCKER_USERNAME as it is not a secret and can be used as a variable
    steps:
      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
  Login_Job:
    needs: docker_job
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        
        # Using secrets for sensitive data
        #  I HAVE Added $DOCKER_PASSWORD as secret at repositroy level/organization level 
        #syntax to access secrets${{secrets.DOCKER_PASSWORD}}
        
        run: echo docker login --username=$DOCKER_USERNAME --password=${{secrets.DOCKER_PASSWORD}}
  Deploy_Job:
    needs: Login_Job
    runs-on: ubuntu-latest
    steps:
        - name: Docker Run
          run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest