name: Job-level variables
on: [push, pull_request]

jobs: 
  docker_job:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      DOCKER_USERNAME: cholaraju29
      IMAGE_NAME: github-actions-nginx
    steps:
      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
      - name: Docker Login
        env:
          DOCKER_PASSWORD: Drycat@29
        # Using secrets for sensitive data
        # ENV AT STEP LEVEL
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      - name: Docker Run
        run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest