name: Workflow-level variables
on: [push, pull_request]  
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: cholaraju29
  IMAGE_NAME: github-actions-nginx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
      - name: Docker Login
        env:
          DOCKER_PASSWORD: Drycat@29
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      - name: Docker Run
        run: echo docker run -d -p 80:80 $CONTAINER_REGISTRY